apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
        - image: ghcr.io/taveek/guestbook:latest
          name: guestbook
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: FOO
              value: bar
            - name: BAR
              value: foo
